# Personalize your website info here
title:            Heather McConnell
tagline:          'Professional Website for Heather McConnell'
description:      'Website and Blog for Heather McConnell'
url:              http://hlmcconnell.github.io
author:
  name:           'Heather McConnell'
  url:            

## You don't need to modify below this line
paginate:         5

# Custom vars
version:          2.1.0
github:
  repo:           https://github.com/poole/hyde

gems: [jekyll-paginate,jekyll-gist, redcarpet]
paginate: 5
paginate_path: "page:num"

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
baseurl:          /
